FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /code

# Copier le fichier des dépendances et installer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source et les tests
COPY app ./app
COPY static ./static
COPY tests ./tests
COPY pyproject.toml ./
COPY pytest.ini ./
COPY .flake8 ./

# Définir PYTHONPATH pour que Python trouve ton app
ENV PYTHONPATH=/code