FROM python:3.12-slim

RUN useradd -m appuser

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

EXPOSE 8000

RUN chown -R appuser:appuser /app

USER appuser

CMD ["sh", "-c", "until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT; do sleep 1; done && uvicorn app.main:app --host 0.0.0.0 --reload"]