name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code quality checks
        run: |
          make check

  test:
    runs-on: ubuntu-latest
    needs: quality

    env:
      TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
      TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
      TEST_POSTGRES_HOST: ${{ secrets.TEST_POSTGRES_HOST }}
      TEST_POSTGRES_PORT: ${{ secrets.TEST_POSTGRES_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start DB and init
        run: |
          docker compose -f docker-compose.test.yml up -d my-test-postgres db-init

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            if docker compose -f docker-compose.test.yml exec -T my-test-postgres \
              pg_isready -U $TEST_POSTGRES_USER -d $TEST_POSTGRES_DB -h $TEST_POSTGRES_HOST; then
              echo "Database is ready!"
              break
            fi
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run tests
        run: docker compose -f docker-compose.test.yml run --rm tests

      - name: Clean up
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

  deploy:
    runs-on: ubuntu-latest
    needs: test

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy app
        run: docker compose -f docker-compose.yml up -d --build
